"""add match_candidates table

Revision ID: 12482657be7a
Revises: 8b6d08f20436
Create Date: 2026-09-29 15:49:03.790836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12482657be7a'
down_revision: Union[str, Sequence[str], None] = '8b6d08f20436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('record_id_1', sa.UUID(), nullable=False),
    sa.Column('record_id_2', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['record_id_1'], ['normalized_vendor_records.id'], ),
    sa.ForeignKeyConstraint(['record_id_2'], ['normalized_vendor_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'record_id_1', 'record_id_2', name='uq_match_pair')
    )
    op.create_index(op.f('ix_match_candidates_batch_id'), 'match_candidates', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_candidates_batch_id'), table_name='match_candidates')
    op.drop_table('match_candidates')
    # ### end Alembic commands ###
