"""add vendor_risk_profiles table

Revision ID: 140131c8e07d
Revises: 83657ead781a
Create Date: 2026-09-29 21:11:29.431700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140131c8e07d'
down_revision: Union[str, Sequence[str], None] = '83657ead781a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_risk_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tax_id', sa.String(length=20), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('sanctions_flag', sa.Boolean(), nullable=False),
    sa.Column('country_risk_tier', sa.String(length=10), nullable=False),
    sa.Column('financial_stability_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('llm_summary', sa.String(length=500), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_risk_profiles')
    # ### end Alembic commands ###
