"""add human_reviews, golden_vendors tables

Revision ID: 83657ead781a
Revises: 90e3fbdb6493
Create Date: 2026-09-29 16:28:21.706372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83657ead781a'
down_revision: Union[str, Sequence[str], None] = '90e3fbdb6493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('golden_vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('human_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_candidate_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('reviewer', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_candidate_id'], ['match_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_candidate_id', name='uq_reviewed_candidate')
    )
    op.add_column('normalized_vendor_records', sa.Column('golden_vendor_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_normalized_vendor_records_golden_vendor_id', 'normalized_vendor_records', 'golden_vendors', ['golden_vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_normalized_vendor_records_golden_vendor_id', 'normalized_vendor_records', type_='foreignkey')
    op.drop_column('normalized_vendor_records', 'golden_vendor_id')
    op.drop_table('human_reviews')
    op.drop_table('golden_vendors')
    # ### end Alembic commands ###
