"""initial schema: raw, normalized, data quality runs

Revision ID: 8b6d08f20436
Revises:
Create Date: 2026-09-29 15:26:53.505369

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8b6d08f20436"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_quality_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=1), nullable=False),
        sa.Column("records_ingested", sa.Integer(), nullable=False),
        sa.Column("records_passed", sa.Integer(), nullable=False),
        sa.Column("records_failed", sa.Integer(), nullable=False),
        sa.Column("issue_counts", sa.JSON(), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_quality_runs_batch_id"), "data_quality_runs", ["batch_id"], unique=False
    )
    op.create_table(
        "normalized_vendor_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=1), nullable=False),
        sa.Column("source_record_id", sa.String(length=50), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("address_line1", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("tax_id", sa.String(length=20), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_record_id", name="uq_source_record"),
    )
    op.create_table(
        "raw_vendor_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=1), nullable=False),
        sa.Column("source_record_id", sa.String(length=50), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("loaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raw_vendor_records_batch_id"), "raw_vendor_records", ["batch_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_raw_vendor_records_batch_id"), table_name="raw_vendor_records")
    op.drop_table("raw_vendor_records")
    op.drop_table("normalized_vendor_records")
    op.drop_index(op.f("ix_data_quality_runs_batch_id"), table_name="data_quality_runs")
    op.drop_table("data_quality_runs")
    # ### end Alembic commands ###
