"""add llm_adjudications table

Revision ID: 90e3fbdb6493
Revises: 12482657be7a
Create Date: 2026-09-29 16:03:10.567242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e3fbdb6493'
down_revision: Union[str, Sequence[str], None] = '12482657be7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_adjudications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_candidate_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_candidate_id'], ['match_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_candidate_id', name='uq_adjudicated_candidate')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_adjudications')
    # ### end Alembic commands ###
