"""Evaluate the latest matching-engine run against the M1 ground truth.

Reports four things, deliberately kept separate because they answer
different questions:
  1. Candidate recall  - did blocking even bring the true duplicates together?
  2. Auto-merge precision/recall - how good is the "fully automated, no
     human or LLM involved" tier on its own?
  3. Pending-review composition - what does the M4/M5 review workload
     actually look like (true dupes vs. true non-dupes)?
  4. Hard-negative leakage - how many of the M1 deliberately-confusable
     non-duplicate pairs got auto-merged? (Target: zero.)

Usage:
    uv run python scripts/evaluate_matching.py
"""

import csv
from pathlib import Path

from sqlalchemy import select

from concord.db.models import MatchCandidate, NormalizedVendorRecord
from concord.db.session import get_session

DATA_DIR = Path("data/synthetic")


def _load_ground_truth_pairs() -> set[frozenset[tuple[str, str]]]:
    pairs = set()
    with (DATA_DIR / "ground_truth_pairs.csv").open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            pairs.add(
                frozenset(
                    {
                        (row["source_1"], row["record_id_1"]),
                        (row["source_2"], row["record_id_2"]),
                    }
                )
            )
    return pairs


def _load_confusable_groups() -> dict[tuple[str, str], tuple[str, str]]:
    """Maps (source, source_record_id) natural key -> (confusable_group_id,
    vendor_id), for every record that has a confusable group. Both fields are
    needed: two records can share a confusable_group_id while still being the
    *same* vendor's own cross-source records (a true match, not leakage) —
    only a shared group with *different* vendor_id is a genuine confusable
    non-duplicate pair."""
    groups: dict[tuple[str, str], tuple[str, str]] = {}
    with (DATA_DIR / "record_index.csv").open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["confusable_group_id"]:
                groups[(row["source"], row["record_id"])] = (
                    row["confusable_group_id"],
                    row["vendor_id"],
                )
    return groups


def main() -> None:
    true_pairs = _load_ground_truth_pairs()
    confusable_groups = _load_confusable_groups()

    session = next(get_session())
    try:
        latest_batch = session.execute(
            select(MatchCandidate.batch_id).order_by(MatchCandidate.created_at.desc()).limit(1)
        ).scalar_one()

        candidates = (
            session.execute(select(MatchCandidate).where(MatchCandidate.batch_id == latest_batch))
            .scalars()
            .all()
        )

        id_to_natural_key = {
            str(row.id): (row.source, row.source_record_id)
            for row in session.execute(select(NormalizedVendorRecord)).scalars().all()
        }
    finally:
        session.close()

    candidate_pairs = set()
    auto_merge_pairs = set()
    pending_review_true = 0
    pending_review_false = 0
    hard_negative_leakage = []

    for c in candidates:
        key_1 = id_to_natural_key[str(c.record_id_1)]
        key_2 = id_to_natural_key[str(c.record_id_2)]
        pair = frozenset({key_1, key_2})
        candidate_pairs.add(pair)
        is_true = pair in true_pairs

        if c.tier == "auto_merge":
            auto_merge_pairs.add(pair)
            group_1 = confusable_groups.get(key_1)
            group_2 = confusable_groups.get(key_2)
            if group_1 and group_2 and group_1[0] == group_2[0] and group_1[1] != group_2[1]:
                hard_negative_leakage.append((key_1, key_2))
        elif c.tier == "pending_review":
            if is_true:
                pending_review_true += 1
            else:
                pending_review_false += 1

    candidate_recall = len(true_pairs & candidate_pairs) / len(true_pairs)
    auto_merge_true_positives = len(auto_merge_pairs & true_pairs)
    auto_merge_precision = (
        auto_merge_true_positives / len(auto_merge_pairs) if auto_merge_pairs else 0.0
    )
    auto_merge_recall = auto_merge_true_positives / len(true_pairs)

    print(f"Batch evaluated: {latest_batch}")
    print(f"True duplicate pairs (ground truth): {len(true_pairs)}")
    print(f"Candidate pairs generated by blocking: {len(candidate_pairs)}")
    print(f"Candidate recall (blocking effectiveness): {candidate_recall:.3f}")
    print()
    print(f"Auto-merge tier: {len(auto_merge_pairs)} pairs")
    print(f"  Precision: {auto_merge_precision:.3f}")
    print(f"  Recall:    {auto_merge_recall:.3f}")
    print()
    print(f"Pending-review tier: {pending_review_true + pending_review_false} pairs")
    print(f"  True duplicates:     {pending_review_true}")
    print(f"  True non-duplicates: {pending_review_false}")
    print()
    print(f"Hard-negative leakage (confusable pairs auto-merged): {len(hard_negative_leakage)}")
    for key_1, key_2 in hard_negative_leakage[:10]:
        print(f"  {key_1} <-> {key_2}")


if __name__ == "__main__":
    main()
